### ISSUE TITLE
Integration of composer.json

### ISSUE THREAD

**Issue by mennen-online** [Baebeca-Solutions/lexoffice-php-api#11]
Hi,

i want to use your package as a composer dependency.

May you can implement this?

**Comment by Elompenta** [comment]
Hi,
of course - this can be a good idea. 👍 

But a question from my side. If i understand it correct you will integrate our product in another product. You can do this, this is no problem but you have to pay attention to the license according "AGPL-3.0".

You can use our codes without a fee only if you publish your code also as open source and your product is using the same "AGPL-3.0" license.
If you don't want to publish your code/product, you can buy a lifetime usage license and get a improved version without the license restrictions.

Can you tell me what do you want to do?
If you will publish a open source project the composer integration is a good idea!
If you will integrate a closed license i need some more specs about your project.

Best regards Basti

**Comment by baekerIT** [comment]
Hi Basti,


i want to develop a Plugin for WordPress one of my customer will need in a few months.

This Plugin will create customers, created in WordPress in Lexoffice too, import orders to lexoffice and synchronize products using webhooks.

Also i want to publish it under AGPL-3.0 - but this depends to my customer at last. I think he will agree to that.


Best Regards

Hendrik

**Comment by Elompenta** [comment]
Hi Hendrik,

sounds good :-) i like your idea!
I see two possible ways:

1. Your customer pay you for the programming work, and buy a usage license for his project. (its a cheap thing, so i think you will not get into trouble with your customer) There is no need to publish the code. (i think the best way)

1. Your customer pay you for the programming work, and you publish the work for free for the world. (So your customer pay to develop a open source solution for everyone) I dont think that your customer wants to to that ;)

**Comment by baekerIT** [comment]
Hi Basti,


yes - the first way is the Best ;-)


So by the way: Developing an open-source Plugin, i would publish it twice: on Github AND the WordPress Plugin Repository.

Before a few years, i already developed a Plugin for SCHUFA Connection between WooCommerce, to verify Peoples identity living in Germany.

**Comment by Elompenta** [comment]
not realy needed at this time. the most people integrate it in there custom codes

**Comment by Elompenta** [comment]
Implemented in Publish as compose package? #39
