### ISSUE TITLE
File Upload - HTTP Status 500

### ISSUE THREAD

**Issue by hatscher** [Baebeca-Solutions/lexoffice-php-api#27]
Beim Versuch des Uploads eines PDF kommt es zu diesem Fehler.

Array ( [HTTP Status] => 500 [Requested URI] => https://api.lexoffice.io/v1/files/ [Requested Payload] => [Response] => )

**Comment by Elompenta** [comment]
@hatscher lexoffice hatte heute Nachmittag ein Performance Problem im Belegupload.

Hier die Meldung von Lexoffice:

> lexoffice Status [Prod]
> [Gelöst] Belegupload/Belegerfassung hat Performanceprobleme 
> Wir haben den Vorfall gelöst. lexoffice ist nun wieder regulär verfügbar. Vielen Dank für Ihre Geduld.
> Dieser Vorfall betrifft: Belegerfassung und Belegerkennung 
> Veröffentlicht am 9 Juni 2020 @ 15:06 CEST

Ich könnte mir gut vorstellen, dass sich das Problem derweil erledigt hat. Kannst du das verifizieren?

**Comment by hatscher** [comment]
Ja, das Problem war darin begründet. Funktioniert nun wieder!
