### ISSUE TITLE
Add method for getting (a single) delivery note

### ISSUE THREAD

**Issue by digitalbricks** [Baebeca-Solutions/lexoffice-php-api#33]
Working recently with your API client (wich is great btw) I noticed that there is no method for getting a single delivery note. I added the method by extending the class but it would be nice to have this integrated into your client:

```php
public function get_deliverynote($uuid) {
        return $this->api_call('GET', 'delivery-notes', $uuid);
}
```

**Comment by Elompenta** [comment]
@digitalbricks Besten Dank, ja stimmt das fehlte noch :-)
Irgendwie brauchte das bisher wohl niemand :-D

Ist drin - https://wiki.baebeca.de/index.php?title=Lexoffice-php-api#Lieferschein_abfragen
