### ISSUE TITLE
Fehler bei Rechnungserstellung

### ISSUE THREAD

**Issue by RobinDev03** [Baebeca-Solutions/lexoffice-php-api#34]
Moin,

immer, wenn ich eine Rechnung erstellen möchte, dann bekomme ich einen Fehler, jedoch kann ich diesen nicht über `$e->get_error()` auslesen, da die Rechnung in der IPN von Paypal / Mollie erstellt wird, sprich die Seite nur von einem WebHook aufgerufen wird.

Ich finde den Fehler irgendwie einfach nicht.

Hier meine Paypal-IPN: https://paste.robin-it.group/xipawivejo.php

Mit freundlichen Grüßen,
Robin & @eliaskyt

**Comment by Elompenta** [comment]
Moin @RobinDev03 und @eliaskyt,

sorry - Support für Code machen wir nur über unser reguläres Ticketsystem (support@baebeca.de), sofern jemand - wie in den Lizenzbedingungen beschrieben - eine Lizenz (90,-/netto/einmalig) hat.

Zumal Nutzer mit Lizenz Ihren Code dann auch nicht offen legen müssen. ;-)
Ansonsten wäre die Frage, wo genau eurer Projekt Quelloffen veröffentlicht wurde?
=> https://github.com/Baebeca-Solutions/lexoffice-php-api#lizenz

Macht doch kurz ein Ticket auf. Das wird man easy debuggen können. Auch trotz Ausführung in als Webhook.

Den Case mache ich zu, da erstmal kein Problem mit der Lösung selbst.

Beste Grüße Basti
