### ISSUE TITLE
ssl_verify is deprecated 

### ISSUE THREAD

**Issue by heri410** [Baebeca-Solutions/lexoffice-php-api#35]
Hi, 

since the update to php 8.2 I get the message

Creation of dynamic property lexoffice_client::$ssl_verify is deprecated in lexoffice-php-api.php on line 31

**Comment by Elompenta** [comment]
Ah nice, thx - it will be fixed soon :-)

**Comment by Elompenta** [comment]
@heri410 fixed in current master branch :-)
