### ISSUE TITLE
Belege via API auf "Bezahlt" setzen

### ISSUE THREAD

**Issue by siach** [Baebeca-Solutions/lexoffice-php-api#5]
Es wäre super, wenn man Belege via API als bezahlt markieren könnte. Momentan gibt es ja nur "draft" oder "open".
Die anderen Zustände der voucherStatus Enum (paid, voided) sind leider Read-only.

Der Hintergrund ist, dass ich über einen Zahlungsdienstleister ein Abo-Modell anbiete. 
Die Rechnung wird also erst erstellt, wenn schon bezahlt wurde.
Mein Workflow auf dem Server ist wie folgt und voll automatisiert: 
- Abo wird abgeschlossen
- Beleg via lexoffice-php-api anlegen
- PDF von jenem Beleg via lexoffice-php-api downloaden
- Email mit Beleg-PDF als Anhang verschicken.
- VERY NICE TO HAVE: Beleg via API als "paid" markieren. Es würde auch reichen, wenn man den Beleg schon beim Erstellen anstatt mit "finalize" auf open irgendwie auf paid setzen könnte.

Momentan nur muss ich noch jede Rechnung von Hand als bezahlt markieren, was bei 150+ Rechnungen pro Monat leider nicht wenig aufwand bedeuted. Mit der oben genannten Funktion könnte der Workflow zu 100% automatisiert werden.

**Comment by Elompenta** [comment]
@siach korrekt - aktuell bietet die Lexoffice Seite diese Funktion noch nicht an.
Wir nehmen das Thema aber mit auf uns besprechen da mit den Entwicklern.

Nur um es richtig zu verstehen. 
Du gehst nicht her und gleichst die Rechnung mit einer Buchung auf dem Konto ab, sondern öffnest den Beleg und klickst auf "Zahlung erfassen". (Zahldatum + Betrag) und drückst dann im Popup auf "Zahlung erfassen" um den Beleg als "bezahlt" zu markieren?

Beste Grüße Basti

**Comment by siach** [comment]
> Nur um es richtig zu verstehen.
> Du gehst nicht her und gleichst die Rechnung mit einer Buchung auf dem Konto ab, sondern öffnest den Beleg und klickst auf "Zahlung erfassen". (Zahldatum + Betrag) und drückst dann im Popup auf "Zahlung erfassen" um den Beleg als "bezahlt" zu markieren?

Genau. 
Der Kunde schließt ein Abo über einen externen Zahlungsdienstleister ab und zahlt sofort mit Paypal oder Kreditkarte. Dann erhalte ich die Kundendaten über die API des Zahlungsdienstleisters. Mit diesen Daten wird dann über die Lexoffice API der Beleg erstellt, welcher aber ja schon bezahlt ist. Anschließend muss ich ihn, wie du beschrieben hast, von Hand als bezahlt markieren.

**Comment by Elompenta** [comment]
Besten Dank für die Erklärung.
Ich habe den Issue entsprechend markiert, dass eine Anpassung seitens Lexoffice nötig ist. 

Sobald uns die neue/erweiterte Methode zur Verfügung steht, stellen wir die Funktion gerne zur Verfügung.

**Comment by Elompenta** [comment]
Wir haben das mit lexoffice besprochen. In diesem Thema gibt es leider _vorerst_ negatives Feedback.
Grund ist die deutsche "GoDB" Richtlinie. ([Wikipedia](https://de.wikipedia.org/wiki/Grunds%C3%A4tze_zur_ordnungsm%C3%A4%C3%9Figen_F%C3%BChrung_und_Aufbewahrung_von_B%C3%BCchern,_Aufzeichnungen_und_Unterlagen_in_elektronischer_Form_sowie_zum_Datenzugriff))

Dies betrifft sowohl das "bezahlt markieren" eines Beleges per API als auch für die "Zuordnung von Transaktion und Belegen" per API.

Das konkrete Problem liegt im Bereich des _Testat_ ([Wikipedia](https://de.wikipedia.org/wiki/Testat)), sprich der granularen Protokollierung und Auswertbarkeit für den Menschen.

Sobald es hier seitens Lexoffice eine für den menschen auszulesene und zu verarbeitende Protokollierung alle API-Anfragen und Aktionen gibt, können wir das Thema gerne noch einmal aufrollen/ansprechen.
Vorerst aber leider nein via API.

Eventuell hätte ich aber eine andere Lösung für dich, die wir dir anbieten könnten :-)
Wenn du mal auf unserer [Website](https://www.baebeca.de/softwareentwicklung/projekte/lexoffice-php-client/) rechts das Formular ausfüllst, könnten wir das im Detail besprechen.
Die Lösung hat nur nichts mit unserer lexoffice-api hier zu tun. Daher würde ich das thematisch trennen wollen.

PS: Das Thema ist nicht vergessen - ich mache hier erstmal einen close, habe das aber weiterhin mit den lexoffice Kollegen auf der Uhr.

Beste Grüße Basti

**Comment by chbister** [comment]
Hallo zusammen,
ist schon eine Weile her, dennoch eine blöde Frage: wo ist der Unterschied zwischen "Offizielle Erweiterung ändert was am Beleg" und "Mein selbstgebautes Skript ändert was am Belegt"? Beide nutzen doch auch nur einen API-Key für authn/authz und menschenlesbar ist in beiden Fällen gleich viel/wenig in den Logs... bei anderen Anbietern für Invoicing (Stripe) geht das doch auch, oder nicht?

**Comment by Elompenta** [comment]
Hallo @chbister 
grundsätzlich sei ersteinmal unterschieden das lexoffice zwei APis hat :-)
Eine die der Endkunde nutzen kann via Key, und eine (mit wesentlich mehr Funktionen) für vertragliche Partner. (So wie wir zum Beispiel mit dem sticky.de Portal)

Als Endkunde gibt es da aktuell keine Chance über die Public API.

Aber mach doch gerne mal ein Ticket bei uns auf mit der Info was konkret du machen möchtest. support@baebeca.de

Wir haben mittlerweile versch. Lösungen die den Zahlstatus von Belegen setzen können.

**Comment by chbister** [comment]
Hallo Sebastian,

vielen Dank für die schnelle Rückmeldung.

Da ich Stripe nutze, möchte ich die bestätigte Transaktion dem Beleg hinzufügen und den Beleg als abgeschlossen markieren. Mein Punkt zu der Sache ist: ich kann per Pubic-API einen Voucher erstellen, kann dazu PDF hochladen, allen möglichen Mist machen - aber keine Zahlung bestätigen. Das halte ich für mindestens schräg ...

Danke für das Angebot. Eine zusätzliche Bezahle-Lösung möchte ich aktuell nicht einsetzen. Ich werde zuerst mal an Lexoffice schreiben.

Grüße
Christian

**Comment by Elompenta** [comment]
Kurz zur Info: Mittlerweile gibt es hier eine Lösung, die wir im Einzelfall anwenden/liefern können, aber kein Bestandteil der offenen Libary ist.
Wer da Interesse/Bedarf hat einfach kurz per support@baebeca.de melden :-)
