### ISSUE TITLE
Return value der Methoden create_invoice() und get_invoice_pdf()

### ISSUE THREAD

**Issue by siach** [Baebeca-Solutions/lexoffice-php-api#6]
Die beiden Methoden create_invoice() und get_invoice_pdf() liefern bei einem Fehler keinen Rückgabewert mehr, da das Script (lexoffice-php-api.php) in Zeile 78 und 108 mit exit() abgebrochen wird.
Damit ist kein Error Handling mehr möglich.

Hintergrund ist, dass ich Belege via API anlege und danach die Beleg-PDF herunterladen muss. Manchmal kommt es vor, dass der Beleg noch nicht erstellt ist und somit der PDF Download fehlschlägt. Würde get_invoice_pdf() in diesem Fall false zurückgeben und nicht das Script mit exit() stoppen, könnte man z.B.: mit einer while Schleife solange get_invoice_pdf() abfragen, bis die Rechnung von Lexoffice erstellt wurde.

**Comment by Elompenta** [comment]
Hallo @siach,
ja das stimmt. Ist vorgemerkt und wird angepasst ;)
Da fehlt noch das wir einen Fehler werfen und man das get_pdf dann mit einem try() macht.

Wird gefixt

Beste Grüße Basti

**Comment by Elompenta** [comment]
Ich habe alle exit's eliminiert ;) Die gehören da nicht hin, da hast du schon recht. 👍 

Ich habe es jetzt so gelöst, dass bei Fehlern eine Exception geworfen wird.

Beispiel:
```
throw new custom_exception('lexoffice-php-api: error in api request - check details via $e->get_error()', array(
  'HTTP Status' => $http_status,
  'Requested URI' => $curl_url,
  'Requested Payload' => json_decode($data),
  'Response' => json_decode($result),
));
```

So kann man mit einem try/catch Block den Fehler abfangen und entsprechend reagieren.
Ich würde hier eine modifizierte Version von "Exception" verwenden, damit wir die API Anfrage inkl. Rückgabe noch mit zurückgeben können.
So kann man mit einem `$e->get_error()` im catch() die zusätzlichen Daten im übergebenen Array auslesen/verwerten/ausgeben o.ä.

Spricht von deiner Seite was dagegen? Wenn das so für dich passt dokumentiere ich das entsprechend und mache einen commit fertig.

Beste Grüße Basti

**Comment by siach** [comment]
Ja, ich denke das ist eine gute Lösung.

**Comment by Elompenta** [comment]
@siach ist wie besprochen umgesetzt und eingecheckt ;)
Doku findest du hier: https://github.com/Baebeca-Solutions/lexoffice-php-api#error-handling

Wichtig ist im catch Block "catch (lexoffice_exception $e)" zu nutzen, da die normale PHP Exception Klasse das "$e->get_error()" nicht kennt.
