### ISSUE TITLE
Datei Upload

### ISSUE THREAD

**Issue by arnemie** [Baebeca-Solutions/lexoffice-php-api#7]
Es wäre absolut klasse wenn der lexoffice-php-client die Möglichkeit des Dateiuploads bieten würde.
Mangels Erfahrung mit Curl in php und der API von lexoffice scheitere ich aktuell leider daran.
Die API von lexoffice bietet die Möglichkeit und der Client würde aus meiner Sicht somit noch sehr viel interessanter werden da sowohl die Eingangs-, als auch Ausgangsbelege automatisch erfasst werden können. 

Noch genialer wäre es, wenn die Belegdaten gleich mit hochgeladen werden könnten, so dass ein nochmaliges Anfassen in der Belegerfassung in Lexoffice überflüssig wäre. Ich denke aber, dass die API aktuelle diese Funktion nicht anbietet.

Vielen Dank an die überaus fleißigen Entwickler hier, der lexoffice-php-client ist echt mega hilfreich!!!

Gruß Arne

**Comment by Elompenta** [comment]
Vielen Dank für dein Feedback! 😀 

Lexoffice unterstützt den Upload von Dateien, das ist richtig.
https://developers.lexoffice.io/docs/#files-endpoint

Aktuell können aber nur Bilder vom Typ "voucher" erstellt werden. (Also Eingangsbelege)
Ich denke das ist wonach du suchst? (Ausgangsbelege werden ja von der Lexoffice für dich erstellt, die brauchst du nicht hochladen)

Wie genau läuft, dass dann bei dir ab? Wie kommen denn gescannte Bilder deiner Rechnungen in deine Anwendung?

**Comment by arnemie** [comment]
Mir geht es dieser Stelle tatsächlich um die Eingangs- UND Ausgangsbelege, da bei mir ein Konstrukt aus verschiedenen Unternehmen vorliegt, bei dem untereinander Rechnungen gestellt und Provisionen abgerechnet werden. Dies soll möglichst automatisiert ablaufen bis hin zur Belegerfassung in den lexoffice-Accounts. Aktuell können über die Lexoffice-API Belege hochgeladen werden, diese werden dann in der Belegerfassungsübersicht zur Auswahl angezeigt. **Und genau hier wäre es super, wenn der lexoffice-php-client diese Funktion bieten würde, da sie für meinen Automatisierungsprozess entscheidend ist** (sonst müsste ich sämtliche Belege zwischen den Accounts immer hoch und runterladen). Zudem kann ich die Provisionsabrechnung nicht als klassiche Rechnung erstellen, daher müssen auch Ausgangsbelege (Einnahme) erfasst werden können.

Das Sahnehäubchen wäre es (wie schon beschrieben), wenn nach dem Dokumentenupload die Belegdaten nicht nochmal im Erfassungsprozess von Hand erstellt werden müssten, sondern der Beleg per API finalisiert werden könnte (Zahlungssatus "open"). Soweit ich das in den docs sehe, bietet die API dieses Sahnehäubchen aktuell nicht (hier wäre vielleicht eine Anregung an lexoffice hilfreich). Ich habe es auch schon kommuniziert. 

Ich hoffe meine Challenge ist verständlich.

**Comment by Elompenta** [comment]
Verstehe :-) Besten Dank für die Erklärung.
Mit Sicherheit eine sinnvolle Erweiterung um auch den Upload von Belegen zu unterstützen.

**Comment by syd1986** [comment]
Ich finde auch, dass dies eine tolle Erweiterung wäre zur Integration von Applikationen die bereits eine PDF Rechnung erzeugen.

**Comment by arnemie** [comment]
Ja, das denke ich auch. Ich hoffe, dass es zeitnah kommen wird. Der API-Client funktioniert in meinen Tests ja super, nur das die Funktion des Beleg uploads sehr zentral für mich und meine Anwendung ist. Solange warte ich noch mit dem geplanten Lizenzerwerb und nutze es nur für Testzwecke.

**Comment by Elompenta** [comment]
Das ist keine große Sache und könnten wir am Wochenende ggf. noch mit releasen ;)

@arnemie Meist hilft der Lizenzerwerb mit einer Info welches Feature man genau braucht. Die Lizenz beinhaltet ja gerade Support und individuelle Weiterentwicklung.

**Comment by Elompenta** [comment]
Das Feature ist eingecheckt und steht zur Verfügung ;)
Die Dokumentation findet sich hier: https://wiki.baebeca.de/index.php?title=Lexoffice-php-api#Beleg_hochladen

**Comment by arnemie** [comment]
Super, vielen Dank. Die Lizenzgeb?hr habe ich gerade angewiesen.
Ich hoffe die Entwicklung geht so weiter.

Eine sch?ne Adventszeit!

Mfg Arne

Am 07.12.2019 um 16:30 schrieb Sebastian <notifications@github.com>:

?

Das Feature ist eingecheckt und steht zur Verf?gung ;)
Die Dokumentation findet sich hier: https://wiki.baebeca.de/index.php?title=Lexoffice-php-api#Beleg_hochladen

-
