### ISSUE TITLE
get_invoice_pdf() invoice not ready ?

### ISSUE THREAD

**Issue by Elompenta** [Baebeca-Solutions/lexoffice-php-api#8]
Separates Problem aus #6

> Hintergrund ist, dass ich Belege via API anlege und danach die Beleg-PDF herunterladen muss. Manchmal kommt es vor, dass der Beleg noch nicht erstellt ist und somit der PDF Download fehlschlägt. Würde get_invoice_pdf() in diesem Fall false zurückgeben und nicht das Script mit exit() stoppen, könnte man z.B.: mit einer while Schleife solange get_invoice_pdf() abfragen, bis die Rechnung von Lexoffice erstellt wurde.

@siach ich konnte das so noch nicht reproduzieren.
Die PDF werden sequentiell erstellt.

Siehe API Beschreibung

> newly created invoices in status open via the API have to trigger the pdf document file rendering separately. This can be done with this endpoint.

Was genau ist denn deine Rückgabe da? Kannst du das reproduzieren?
Das könnten wir ja direkt schon im Client für jedermann abfangen ;)

**Comment by siach** [comment]
Das war nicht korrekt ausgeführt von mir.
Wenn ich einen Beleg als Entwurf erstelle, lässt er sich mit get_invoice_pdf() nicht abfragen, was ja auch so in der Lexoffice API dokumentiert ist. Allerdings wird dann (noch) das exit() aufgerufen anstatt eine Fehlermeldung.

**Comment by Elompenta** [comment]
Achso, das meinst du :-)
Da macht es ja mehr Sinn, wenn wir diesen Fehler im Client abfangen und ebenso eine Exception werfen, wenn das der Fall ist.

Dann kann der User sich überlegen ob der die Rechnung fertigstellt oder nicht.
Wird gefixt :)

**Comment by Elompenta** [comment]
@siach Wir prüfen das nun direkt im Client und werfen bei Bedarf eine passende Exception die man abfangen kann.

`lexoffice-php-api: requested invoice is a draft. Cannot create/download pdf file. Check details via $e->get_error()`

Ein "$e->get_error()" gibt dann Erkenntnis darüber welche ID nicht funktioniert hat:
```
Array (
    [invoice_id] => ee6b0629-9794-4501-8e04-fc39911eef2e
)
```

Ist eingecheckt ;)
